### NumPy flip()

In [2]:
import numpy as np

In [3]:
arr = np.array([2, 4, 6, 8, 10])
arr2 = np.flip(arr)
arr2

array([10,  8,  6,  4,  2])

In [5]:
# Example 2: Use numpy flip() function with 2-d arrays
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.flip(arr)
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
arr2 = np.flip(arr, axis=1)
print(arr2)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [7]:
# Use numpy flip() with axis=0
arr2 = np.flip(arr, axis=0)
print(arr2)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### slicing with flip()

In [8]:
# Use slicing with flip() 
arr2 = np.flip(arr[:,1])
print(arr2)

[8 5 2]


In [9]:
# Get the single uniform random sample
arr = np.random.uniform()
print(arr)

0.888308049730009


In [10]:
# Get the uniform samples of an array
arr = np.random.uniform(size = 5)
print(arr)

[0.3169651  0.70469042 0.24157592 0.63791647 0.8967686 ]


In [16]:
# Get the uniform random samples
arr = np.random.uniform(low = 3, high = 5, size = 4)
print(arr)

[3.76571493 3.98503397 4.92127682 3.09863576]


In [18]:
arr = np.array([4, 7, 2, 4, 3])
  
# Padding array using Constant mode
arr1 = np.pad(arr, (3, 2), 'constant', constant_values=(8,0))                 
print(arr1)


[8 8 8 4 7 2 4 3 0 0]


In [19]:
arr2 = np.pad(arr, (2, 3), 'edge')
print(arr2)


[4 4 4 7 2 4 3 3 3 3]


In [21]:
# Example 1: Index with the largest value
arr = np.array([4,7,2,9,12,16,19])
arr2 = np.argmax(arr)
arr2

6